### ISSUE TITLE
UndefVarError: is_return not defined

### ISSUE THREAD

**Issue by alyst** [JuliaDebug/LoweredCodeUtils.jl#39]
I'm getting this error when trying to precompile *Revise.jl* (Julia 1.4.2; packages freshly updated).
It looks like *is_return()* function was not included in the recently merged #38, since the latter replaces `isexpr(node, :return)` with `is_return(node)`, but I don't see this function being defined.

**Comment by timholy** [comment]
What are your package versions? You may need to do `add Revise@2; pin Revise`.

**Comment by alyst** [comment]
> What are your package versions?

In the project environment there were the uptodate ones: *Revise* v2.6.7, *LoweredCodeUtils* v0.4.6, *JuliaInterpreter* v0.7.23.
But I'm using Juno, and in the startup *v1.4* env it was the old (v0.7.16) *JuliaInterpreter*. Probably that was the reason of the error.
After I updated *v1.4* packages, the error is gone.
